# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '\\hal\tools\scripts\python\utilities\remote_auto_publish\rap_ui\remote_auto_publish_UI.ui'
#
# Created: Thu Aug 03 15:24:50 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_RemoteAutoPublish(object):
    def setupUi(self, RemoteAutoPublish):
        RemoteAutoPublish.setObjectName("RemoteAutoPublish")
        RemoteAutoPublish.resize(700, 271)
        RemoteAutoPublish.setMinimumSize(QtCore.QSize(700, 271))
        RemoteAutoPublish.setMaximumSize(QtCore.QSize(700, 271))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(RemoteAutoPublish)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtGui.QLabel(RemoteAutoPublish)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtGui.QLabel(RemoteAutoPublish)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.line = QtGui.QFrame(RemoteAutoPublish)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.label_7 = QtGui.QLabel(RemoteAutoPublish)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.watch_folder = QtGui.QLineEdit(RemoteAutoPublish)
        self.watch_folder.setObjectName("watch_folder")
        self.horizontalLayout_4.addWidget(self.watch_folder)
        self.browse = QtGui.QPushButton(RemoteAutoPublish)
        self.browse.setObjectName("browse")
        self.horizontalLayout_4.addWidget(self.browse)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.label_6 = QtGui.QLabel(RemoteAutoPublish)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.set_days = QtGui.QSpinBox(RemoteAutoPublish)
        self.set_days.setObjectName("set_days")
        self.horizontalLayout_3.addWidget(self.set_days)
        self.set_hours = QtGui.QSpinBox(RemoteAutoPublish)
        self.set_hours.setObjectName("set_hours")
        self.horizontalLayout_3.addWidget(self.set_hours)
        self.set_minutes = QtGui.QSpinBox(RemoteAutoPublish)
        self.set_minutes.setObjectName("set_minutes")
        self.horizontalLayout_3.addWidget(self.set_minutes)
        self.set_seconds = QtGui.QSpinBox(RemoteAutoPublish)
        self.set_seconds.setObjectName("set_seconds")
        self.horizontalLayout_3.addWidget(self.set_seconds)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(RemoteAutoPublish)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.days_timer = QtGui.QLCDNumber(RemoteAutoPublish)
        self.days_timer.setProperty("intValue", 0)
        self.days_timer.setObjectName("days_timer")
        self.verticalLayout.addWidget(self.days_timer)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtGui.QLabel(RemoteAutoPublish)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.hours_timer = QtGui.QLCDNumber(RemoteAutoPublish)
        self.hours_timer.setObjectName("hours_timer")
        self.verticalLayout_2.addWidget(self.hours_timer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(RemoteAutoPublish)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.minutes_timer = QtGui.QLCDNumber(RemoteAutoPublish)
        font = QtGui.QFont()
        font.setFamily("Modern")
        self.minutes_timer.setFont(font)
        self.minutes_timer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.minutes_timer.setObjectName("minutes_timer")
        self.verticalLayout_3.addWidget(self.minutes_timer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtGui.QLabel(RemoteAutoPublish)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.seconds_timer = QtGui.QLCDNumber(RemoteAutoPublish)
        self.seconds_timer.setSizeIncrement(QtCore.QSize(0, 0))
        self.seconds_timer.setSmallDecimalPoint(False)
        self.seconds_timer.setObjectName("seconds_timer")
        self.verticalLayout_4.addWidget(self.seconds_timer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QtGui.QPushButton(RemoteAutoPublish)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.stop_btn = QtGui.QPushButton(RemoteAutoPublish)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtGui.QLabel(RemoteAutoPublish)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.database = QtGui.QTreeWidget(RemoteAutoPublish)
        self.database.setObjectName("database")
        self.database.headerItem().setText(0, "1")
        self.verticalLayout_7.addWidget(self.database)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.label_2.setBuddy(self.set_days)
        self.label_3.setBuddy(self.set_hours)
        self.label_4.setBuddy(self.set_minutes)
        self.label_5.setBuddy(self.set_seconds)

        self.retranslateUi(RemoteAutoPublish)
        QtCore.QMetaObject.connectSlotsByName(RemoteAutoPublish)

    def retranslateUi(self, RemoteAutoPublish):
        RemoteAutoPublish.setWindowTitle(QtGui.QApplication.translate("RemoteAutoPublish", "Remote Auto Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Remote File Auto-Publisher", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Auto-Publish files to Shotgun using a watch folder. Folder structure uses active projects in the Shotgun database to publish new files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Watch Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.watch_folder.setText(QtGui.QApplication.translate("RemoteAutoPublish", "C:/Users/adamb/Documents/dropbox", None, QtGui.QApplication.UnicodeUTF8))
        self.browse.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Set Timer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Days", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Hours", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.start_btn.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_btn.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("RemoteAutoPublish", "Watch Folder Data Record", None, QtGui.QApplication.UnicodeUTF8))

